<?php
function getSearch($links, $search){
    $result = array();
    foreach($links as $link) {
        $encoded_url = base64_encode($link[0]);
        $saved_path ='save/'. $encoded_url.'.json';
        // check file exists
        
        if (is_file( $saved_path ) ) {
        $saved_article =Page::deserialize( file_get_contents($saved_path) );
        $content = $saved_article->getContent();
        $category = $saved_article->getCategory();
        $source = $saved_article->getSource();
        // echo($content.'<hr>');
        $similarty = compareStrings($content,$search); 
        ($similarty > 0)? array_push($result,array($link[0],$category,$source,$similarty)) : '';
        }
        //rank sort result if more than one
        
    }

    if(sizeof($result) > 1){
        return msort($result,3);
    }
    return $result;

}

function msort($array, $id) {
    $temp_array = array();
    while(count($array)>0) {
        $lowest_id = 0;
        $index=0;
        foreach ($array as $item) {
            if ($item[$id]>$array[$lowest_id][$id]) {
                $lowest_id = $index;
            }
            $index++;
        }
        $temp_array[] = $array[$lowest_id];
        $array = array_merge(array_slice($array, 0,$lowest_id), array_slice($array, $lowest_id+1));
    }
    return $temp_array;
}

function compareStrings($s1, $s2) {
    //one is empty, so no result
    if (strlen($s1)==0 || strlen($s2)==0) {
        return 0;
    }

    //replace none alphanumeric charactors
    //i left - in case its used to combine words
    $s1clean = preg_replace("/[^A-Za-z0-9-]/", ' ', $s1);
    $s2clean = preg_replace("/[^A-Za-z0-9-]/", ' ', $s2);

    //remove double spaces
    while (strpos($s1clean, "  ")!==false) {
        $s1clean = str_replace("  ", " ", $s1clean);
    }
    while (strpos($s2clean, "  ")!==false) {
        $s2clean = str_replace("  ", " ", $s2clean);
    }
    //Convert all strings to uppercase
    $s1clean = strtoupper($s1clean);
    $s2clean = strtoupper($s2clean);

    //create arrays
    $ar1 = explode(" ",$s1clean);
    $ar2 = explode(" ",$s2clean);

    //flip array 2, to make the words the keys
    $ar2 = array_flip($ar2);


    $maxwords = count($ar1);
    $matches = 0;

    //find matching words
    foreach($ar1 as $word) {
        if (array_key_exists($word, $ar2))
            $matches++;
    }
    // echo('<hr> Number of words in Article :'.$maxwords.' Matches :'.$matches);
    
    unset($s1clean,$s2clean,$ar1,$ar2,$l1,$l2);
    return round(($matches / $maxwords) * 100,3);    
}

function startEnd($source,$category){
    if($source == 'My Joy Online'){
        return array('<!-- /1002554/Myjoyonline/mjo-category-leaderboard_top -->','We recommend');
    }elseif ($source == 'GhanaWeb') {
        if($category == 'Business'){
            return array('<!-- End of html generated by this->header() -->','<div class="column2 noTop">');
        }elseif($category == 'News'){array('column2','rightsection');}
        elseif($category == 'News'){array('column2','column1');}
        elseif($category == 'Entertainment'){array('column1','column2');}
        elseif($category == 'World'){array('<!-- End of html generated by this->header() -->','<!-- Start of html generated by this->footer() -->');}
    }
    else{
        if($category=='Business'){return array('<!-- .top-menu /-->','<!-Currency Converter widget - HTML code - fx-rate.net -->');}
        elseif ($category=='Politics') {return array('<!--Main Content-->','</div><!--Main Content-->');}
        else{return array('<!--Main Content-->','</div><!--Main Content-->');}
    }
}

function getRecent($links='', $limit=true){
    if($limit){

        $links = array(
            array('https://www.myjoyonline.com/ghana-news/business.php','Business','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/politics.php','Politics','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/news.php','News','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/entertainment.php','Entertainment','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/opinion.php','Opinion','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/lifestyle.php','Life style','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/world.php','World','My Joy Online'),
            array('https://www.myjoyonline.com/ghana-news/sports.php','Sport','My Joy Online'),
            
            array('http://citibusinessnews.com/','Business','Citi News Room'),
            array('https://citinewsroom.com/ghana-news/politics/','Politics','Citi News Room'),
            // array('https://www.myjoyonline.com/ghana-news/news.php','News','Citi News Room'),
            array('https://citinewsroom.com/ghana-news/showbiz/','Entertainment','Citi News Room'),
            array('https://citinewsroom.com/ghana-news/opinion/','Opinion','Citi News Room'),
            array('https://citinewsroom.com/ghana-news/relationship/','Life style','Citi News Room'),
            // array('https://www.myjoyonline.com/ghana-news/world.php','World','Citi News Room'),
            array('https://citinewsroom.com/ghana-news/sports/','Sport','Citi News Room'),

            array('https://www.ghanaweb.com/GhanaHomePage/business/','Business','GhanaWeb'),
            array('https://www.ghanaweb.com/GhanaHomePage/SportsArchive/','Sport','GhanaWeb'),
            array('https://www.ghanaweb.com/GhanaHomePage/NewsArchive/','News','GhanaWeb'),
            array('https://www.ghanaweb.com/GhanaHomePage/entertainment/','Entertainment','GhanaWeb'),
            array('https://www.ghanaweb.com/GhanaHomePage/world/','World','GhanaWeb')

        );
    }

    
    $array = array();
    foreach($links as $scrap_url){
        $str = startEnd($scrap_url[2],$scrap_url[1]);
        $start_str = $str[0];
        $end_str = $str[1];
        $recent = downloadRecent($scrap_url,$start_str,$end_str, $limit);
        if(!in_multiarray($recent, $array) && !empty($recent)){
        array_push($array, array($recent,$scrap_url[1],$scrap_url[2])); 
        }
    }
    
    return $array;
}
function downloadArticle($links,$category="",$source="") {
    $pageScraper = new Pagescraper;
    
    if(is_array($links)){
        foreach($links as $link){
            $pageScraper->getArticle($link,$category,$source);
        }
    }
    else{
        $pageScraper->getArticle($links,$category,$source);
    }
   
}


function is_connected(){
    $connected = @fsockopen($scrap_url, 80); 
    if ($connected){
        fclose($connected);
        return "true";
    }else{
        return "false";
    }
}

function in_multiarray($elem, $array){
    $top = sizeof($array) - 1;
    $bottom = 0;
    while($bottom <= $top){
        if($array[$bottom] === $elem){
            return true;
        }
        else{ 
            if(is_array($array[$bottom])){
                if(in_multiarray($elem, ($array[$bottom]))){
                    return true;
                }
            }
        }   
        $bottom++;
    }        
    return false;
}

function curl_download($Url,$start_str,$end_str,$limit = false){
  
    if (!function_exists('curl_init')){
        die('cURL is not installed. Install and try again.');
    }    

    $curl_resourse = curl_init();
    curl_setopt($curl_resourse, CURLOPT_URL, $Url);
    curl_setopt($curl_resourse, CURLOPT_RETURNTRANSFER, true);
    $output = curl_exec($curl_resourse);
    curl_close($curl_resourse);
    $start = strpos($output, $start_str);
    $end = strpos($output, $end_str, $start);
    $length = $end-$start;
    ($limit)? $length = $length/2: '';
    $output = substr($output, $start, $length);
  
    return $output;
}

function blacklist($link){
    $re = '/\/author\//m';
    preg_match($re, $link, $matches);
    if(strpos($link, 'inner.php') !== false || strlen($link) < 5 || !empty($matches[0])){
        return true;
    }
    else{
        return false;
    }
}

function linkExtractor($html,$linkArray = array(),$limit=false,$source='') {
 
 $linkArray1 = array();
 $black_list = array(
    'javascript:void(0);','videos.php',
    'https://www.myjoyonline.com/news/2018/July-10th/video-police-bust-10-nigerians-5-ghanaians-and-1-liberian-in-sex-swoop.php',
    'inner.php?section=business&category=finance',
    'https://citinewsroom.com/author/jonas/',
    'https://citinewsroom.com/author/farida/',
    'https://citinewsroom.com/author/allotey/',
    'inner.php?section=business&category=banking'
   );

if(preg_match_all("/a[\s]+[^>]*?href[\s]?=[\s\"\']+".
"(.*?)[\"\']+.*?>"."([^<]+|.*?)?<\/a>/", $html, $matches, PREG_SET_ORDER)){
    if($limit){
        foreach ($matches as $match) {
            if(trim($match[1]) != "" &&trim($match[2]) != "" && !in_array($match[1], $black_list) && !blacklist($match[1])){
                if($source=='GhanaWeb'){
                    $m = "https://www.ghanaweb.com/".$match[1];
                    array_push($linkArray, $m);
                }else{
                    array_push($linkArray, $match[1]);
                }
                break;
            }
            
        }
    }
    else{
        foreach ($matches as $match) {
            if(trim($match[2]) != "" && !in_array($match[1], $black_list) && !blacklist($match[1])){
              
               if(!in_multiarray($match[1], $linkArray)){
                   array_push($linkArray, array($match[1]));
               }
            }
        }
    }
 
}

 return $linkArray;
}

function display($allLinks){
    $downloadArray = array();
    foreach($allLinks as $link){
    
        //downloaded links
        $encoded_url = base64_encode($link[0]);
        $saved_path = './save/'.$encoded_url.'.json';
        // check file exists
        if (is_file( $saved_path ) ) {           
            array_push($downloadArray, array($link[0], $link[1]));         
        }
        else {
            echo '<h2 ><a href="pagescrape.php?targetUrl='. $link[0] .'">'. $link[1] .'</a></h2><hr>';
        }
    }
    echo '<h1><em>Downloaded</em></h1>';
    foreach($downloadArray as $link){
        echo '<h2 ><a href="pagescrape.php?targetUrl='. $link[0] .'">'. $link[1] .'</a></h2><hr>';
    }

}

function downloadRecent($arr_scrap_url,$start_str,$end_str, $limit=false){
    // $scrap_url = 'https://www.myjoyonline.com/ghana-news/business.php';
    // $start_str = '<div id="wrapper" class="wide">';
    // $end_str = 'We recommend';
    $scrap_url = $arr_scrap_url[0];
    $category  = $arr_scrap_url[1];
    $source    = $arr_scrap_url[2];

    if(is_connected()){

        $allLinks = array();
        $allLinks = linkExtractor(curl_download($scrap_url,$start_str,$end_str,$limit), $allLinks,$limit,$source);//var_dump($allLinks);die('ello');
        downloadArticle($allLinks,$category,$source);

        foreach ($allLinks as $links){save_news($links[0]);}
        return $allLinks;
    }
    else{
      return '';  
    }

}

function merge_r($allLinks,$string_data){
    foreach ($allLinks as $links){
        if(!in_multiarray($links, $allLinks)){
            array_push($allLinks, $links);
        }
    }
}

function save_news($link){
    // var_dump($link);
    (is_array($link))? $link = $link[0]:'';
                $txt_content ='
                <?php 
                $pageScraper = new Pagescraper;
                $article = $pageScraper->getArticle("'. $link .'");  
                ?>
            <div class="columns">

                        
            <div class="view-controls">
                <a class="pull-left" href="#"><i class="fa fa-hand-o-left"></i> Previous</a>

                <a class="pull-right" href="#">Next <i class="fa fa-hand-o-right"></i></a>
                <br style="clear: both;">
            </div>
            </div>
            <article class="post type-post status-publish format-standard has-post-thumbnail hentry category-themes">
                <div class="entry-image" style=""> 
                <a class="image-comment" title="<?php echo $article->getTitle(); ?>" rel="bookmark"> 
                <img src=" <?php echo $article->getImage(); ?>" class="attachment-sidebar-large size-sidebar-large wp-post-image" alt="">
                </a>
                </div>
                <div class="entry-container box">
                    <div class="post-title author-image-on">
                        <h1 class="entry-title">
                        <a>
                        <?php echo $article->getTitle(); ?>
                        </a></h1>
                        <div class="post-meta">
                            <ul>
                                <li>
                                    <time class="entry-date updated" datetime="<? echo ( $article->getTitle() !== null )? date("M j, Y",strtotime($article->getDate())):""; ?>"> <? echo ( $article->getTitle() !== null )? date("M j, Y",strtotime($article->getDate())):""; ?></time>
                                </li>
                                <li class="divider">/</li>
                                <li>:: <a target="_blank" href="https://www.myjoyonline.com"><?echo ($article->getSource() !==null)? $article->getSource(): ""; ?></a> ::</li>
                            </ul>
                        </div>
                    </div>
                    <div class="entry-content entry-content2" lang="en">
                        <p class="snb-content"></p>
                        <?php echo $article->getContent(); ?>
                        <p></p>
                        <!-- <p> <a target="_blank" href="" class="more-link"> Open Full Story&#8230;</a></p> -->
                        <footer class="entry-meta clearfix">
                            <ul class="post-tags clearfix">
                                <li><a class="cat-item-link" data-href="agency-2" rel="tag"><?echo ($article->getSource() !==null)? $article->getSource(): ""; ?></a></li>
                                <li><a class="cat-item-link" data-href="News" rel="tag">News</a></li>
                                                                                    <li><a class="cat-item-link" data-href="Business" rel="tag">Business</a></li>
                                                                            </ul>
                        </footer>
                    </div>
                </div>
            </article>
            </div>
            ';

        
  
            
        $encoded_url = base64_encode($link);
        $saved_path = './news/'.$encoded_url.'.php';
        $saved_path1 = './save/'.$encoded_url.'.json';
        // check file exists
        if (!is_file( $saved_path1 ) ) { 
            downloadArticle($link);
        }
   
        
        // check file exists
        if (is_file( $saved_path ) ) {
        // return the save files contents
            return $saved_path;
        }

        if(file_put_contents($saved_path, $txt_content)){
            return $saved_path;
        }
        die("errr");
    return '#';
}
?>